apiVersion: v1
kind: Namespace
metadata:
  name: pogokwetter
  labels:
    name: pogokwetter
---
apiVersion: v1
kind: Service
metadata:
  name: pokemonread-service
  namespace: pogokwetter
  labels:
    app: pokemonread-service
    tier: backend
spec:
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: pokemonread-service
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemonread-service
  namespace: pogokwetter
spec:
  selector:
    matchLabels:
      app: pokemonread-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: pokemonread-service
        tier: backend
    spec:
      containers:
        - name: pokemonread-service
          image: ghcr.io/teunbuis-semester6-pogokwetter/pokemonread-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
---